name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: [ focal ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
